name: Build libnode
description: Build and upload libnode prebuilt artifacts

runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.4.0
      with:
        node-version: "24"

    - name: Setup pnpm environment
      env:
        KF_SKIP_FALLBACK_BUILD: true
      shell: bash
      run: corepack pnpm install --frozen-lockfile

    - name: Make libnode
      shell: bash
      # Workaround for gyp not able to find nasm.exe when run on GitHub Windows runner
      run: corepack pnpm make

    - name: Build
      env:
        KF_SKIP_MAKE_LIBNODE: true
      shell: bash
      run: corepack pnpm build

    - name: Package
      shell: bash
      run: corepack pnpm package

    - name: Upload
      uses: actions/upload-artifact@v7.0.1
      with:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        name: "libnode-${{env.BUILDER_OS}}-${{github.actor}}-${{github.sha}}"
        path: |
          **/build/stage/*/v*/v*/*.*
